---

- name: Install kubernetes.core in pip
  pip:
    name:
      - kubernetes
  delegate_to: localhost

- name: Get node info
  kubernetes.core.k8s_info:
    kind: Node
    name: "{{ inventory_hostname }}"
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  register: node_info
  failed_when: false
  changed_when: false

- name: Update Node
  block:
    - name: Cordon and drain node
      include_tasks: drain.yml

    - name: Upgrade the operating system
      include_tasks: "{{ k8s_os | lower }}.yml"

    - name: Uncordon node
      include_tasks: uncordon.yml
  when:
    # node condition is Ready
    - node_info.resources[0] | json_query("status.conditions[?type == 'Ready'].status")
    # node spec does not contain unschedulable attribute
    - not (node_info.resources[0].spec.unschedulable is defined)
